"""empty message

Revision ID: 0da6e4b047d4
Revises: f234cf616a3c
Create Date: 2020-06-17 22:40:33.890601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da6e4b047d4'
down_revision = 'f234cf616a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_agreement', sa.Column('rental_objcet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rental_agreement', 'rental_object', ['rental_objcet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rental_agreement', type_='foreignkey')
    op.drop_column('rental_agreement', 'rental_objcet_id')
    # ### end Alembic commands ###
