"""empty message

Revision ID: 22537ce8d386
Revises: 5b1a57923806
Create Date: 2020-06-17 22:54:55.153855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22537ce8d386'
down_revision = '5b1a57923806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rent_bill',
    sa.Column('date_of_payment', sa.DATE(), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('rental_agreement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rental_agreement_id'], ['rental_object.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'rental_agreement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rent_bill')
    # ### end Alembic commands ###
