"""empty message

Revision ID: 4762fc11605f
Revises: eac8e45c438e
Create Date: 2020-06-17 21:36:07.636983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4762fc11605f'
down_revision = 'eac8e45c438e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('rental_object_id', sa.Integer(), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flat_id'], ['flat.id'], ),
    sa.ForeignKeyConstraint(['rental_object_id'], ['rental_object.id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.drop_constraint('rental_object_flat_id_fkey', 'rental_object', type_='foreignkey')
    op.drop_constraint('rental_object_rental_object_id_fkey', 'rental_object', type_='foreignkey')
    op.drop_column('rental_object', 'flat_id')
    op.drop_column('rental_object', 'rental_object_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_object', sa.Column('rental_object_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('rental_object', sa.Column('flat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('rental_object_rental_object_id_fkey', 'rental_object', 'rental_object', ['rental_object_id'], ['id'])
    op.create_foreign_key('rental_object_flat_id_fkey', 'rental_object', 'flat', ['flat_id'], ['id'])
    op.drop_table('room')
    # ### end Alembic commands ###
