"""empty message

Revision ID: 570774825fc5
Revises: 4762fc11605f
Create Date: 2020-06-17 21:43:42.530318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570774825fc5'
down_revision = '4762fc11605f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('room_rental_object_id_fkey', 'room', type_='foreignkey')
    op.drop_constraint('room_flat_id_fkey', 'room', type_='foreignkey')
    op.create_foreign_key(None, 'room', 'rental_object', ['id'], ['id'])
    op.drop_column('room', 'flat_id')
    op.drop_column('room', 'room_id')
    op.drop_column('room', 'rental_object_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('rental_object_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('room', sa.Column('room_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('room', sa.Column('flat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.create_foreign_key('room_flat_id_fkey', 'room', 'flat', ['flat_id'], ['id'])
    op.create_foreign_key('room_rental_object_id_fkey', 'room', 'rental_object', ['rental_object_id'], ['id'])
    op.drop_column('room', 'id')
    # ### end Alembic commands ###
