"""empty message

Revision ID: 5b1a57923806
Revises: 0da6e4b047d4
Create Date: 2020-06-17 22:53:47.869693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1a57923806'
down_revision = '0da6e4b047d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_agreement', sa.Column('rental_object_id', sa.Integer(), nullable=True))
    op.drop_constraint('rental_agreement_rental_objcet_id_fkey', 'rental_agreement', type_='foreignkey')
    op.create_foreign_key(None, 'rental_agreement', 'rental_object', ['rental_object_id'], ['id'])
    op.drop_column('rental_agreement', 'rental_objcet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_agreement', sa.Column('rental_objcet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rental_agreement', type_='foreignkey')
    op.create_foreign_key('rental_agreement_rental_objcet_id_fkey', 'rental_agreement', 'rental_object', ['rental_objcet_id'], ['id'])
    op.drop_column('rental_agreement', 'rental_object_id')
    # ### end Alembic commands ###
