"""empty message

Revision ID: 70561073e573
Revises: 22537ce8d386
Create Date: 2020-06-19 18:13:53.473197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70561073e573'
down_revision = '22537ce8d386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_constraint('rent_bill_rental_agreement_id_fkey', 'rent_bill', type_='foreignkey')
    op.create_foreign_key(None, 'rent_bill', 'rental_agreement', ['rental_agreement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rent_bill', type_='foreignkey')
    op.create_foreign_key('rent_bill_rental_agreement_id_fkey', 'rent_bill', 'rental_object', ['rental_agreement_id'], ['id'])
    op.drop_column('group', 'name')
    # ### end Alembic commands ###
