"""empty message

Revision ID: a03c3e2ec1e0
Revises: 26143e859d81
Create Date: 2020-06-16 12:30:38.002677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03c3e2ec1e0'
down_revision = '26143e859d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('pesel', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('surname', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['pesel'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'pesel')
    op.drop_column('user', 'name')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
