"""empty message

Revision ID: e1fac486ff0a
Revises: a03c3e2ec1e0
Create Date: 2020-06-16 12:31:53.971911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fac486ff0a'
down_revision = 'a03c3e2ec1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlord', sa.Column('bank_account_number', sa.String(length=16), nullable=True))
    op.create_unique_constraint(None, 'landlord', ['bank_account_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'landlord', type_='unique')
    op.drop_column('landlord', 'bank_account_number')
    # ### end Alembic commands ###
