"""empty message

Revision ID: eac8e45c438e
Revises: 96110a91786e
Create Date: 2020-06-17 21:35:33.821660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac8e45c438e'
down_revision = '96110a91786e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    op.add_column('rental_object', sa.Column('flat_id', sa.Integer(), nullable=True))
    op.add_column('rental_object', sa.Column('rental_object_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rental_object', 'rental_object', ['rental_object_id'], ['id'])
    op.create_foreign_key(None, 'rental_object', 'flat', ['flat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rental_object', type_='foreignkey')
    op.drop_constraint(None, 'rental_object', type_='foreignkey')
    op.drop_column('rental_object', 'rental_object_id')
    op.drop_column('rental_object', 'flat_id')
    op.create_table('room',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('flat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['flat_id'], ['flat.id'], name='room_flat_id_fkey'),
    sa.ForeignKeyConstraint(['id'], ['rental_object.id'], name='room_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='room_pkey')
    )
    # ### end Alembic commands ###
