"""empty message

Revision ID: f234cf616a3c
Revises: 570774825fc5
Create Date: 2020-06-17 22:35:21.116963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f234cf616a3c'
down_revision = '570774825fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('rules_of_use', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('common_agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['rental_agreement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occasional_agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notary_confirmation', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['rental_agreement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('occasional_agreement')
    op.drop_table('common_agreement')
    op.drop_table('rental_agreement')
    # ### end Alembic commands ###
