"""empty message

Revision ID: fee11cbbdd23
Revises: e1fac486ff0a
Create Date: 2020-06-16 14:49:59.675068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee11cbbdd23'
down_revision = 'e1fac486ff0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'pesel',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user_group', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_group', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_group', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_group', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'pesel',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
